# Generated by Django 3.2.7 on 2021-10-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='lastname',
            field=models.CharField(max_length=100),
        ),
    ]
