# Generated by Django 3.2.7 on 2021-10-05 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_auto_20211005_1940'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SignupForm',
            new_name='User',
        ),
    ]
