# Generated by Django 3.2.7 on 2021-10-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0002_auto_20211004_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated date'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
