# Generated by Django 3.2.7 on 2021-10-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0003_auto_20211005_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='user_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
