# Generated by Django 3.2.7 on 2021-10-06 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0004_notes_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notes',
            new_name='createnotes',
        ),
    ]
