# Generated by Django 3.2.7 on 2021-10-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0005_rename_notes_createnotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createnotes',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='createnotes',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='createnotes',
            name='user_id',
            field=models.TextField(blank=True),
        ),
    ]
