# Generated by Django 3.2.7 on 2021-10-11 14:59

import Notes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0006_auto_20211007_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createnotes',
            name='image',
            field=models.ImageField(blank=True, upload_to=Notes.models.get_file_path),
        ),
    ]
